#!/usr/bin/env node

require.paths.push(__dirname + '/lib');

var buster = require("buster");
var glob = require("glob");

glob.glob("test/**/*-test.js", function (err, files) {
    files.forEach(function (f) { require("./" + f); });
});
